joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 0.9

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.3
    scale_angular_turbo:
      yaw: 0.9


    enable_button: 5 
    enable_turbo_button: 4

    require_enable_button: false   

  # comment above line to disable deadman switch